### ISSUE TITLE
图片都打不开

### ISSUE THREAD

**Issue by lizhe422** [datawhalechina/free-excel#1]
可以把图片都重新上传一下么？

**Comment by yangjiada** [comment]
第几章的呢 目前更新到第二章 目录下image有图片




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "datawhalechina/free-excel"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月15日(星期二) 上午10:59
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[datawhalechina/free-excel] 图片都打不开 (Issue #1)





 
可以把图片都重新上传一下么？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
